### ISSUE TITLE
Unable to import porekit due to ImportError

### ISSUE THREAD

**Issue by adelq** [akloster/porekit-python#1]
OS: Linux x86_64

Steps to reproduce:

    import porekit

Expected: No error

Result:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-78fda1c2b655> in <module>()
----> 1 import porekit
      2 import pandas as pd
      3 import numpy as np
      4 import seaborn as sb
      5 import matplotlib.pyplot as plt

~/.local/lib/python3.5/site-packages/porekit/__init__.py in <module>()
     10 from .porekit import gather_metadata, Fast5File, make_squiggle
     11 from . import plots
---> 12 from . import sim

ImportError: cannot import name 'sim'
```

I looked around in the repository, but couldn't find any `sim.py` or similar.

**Comment by akloster** [comment]
I have abandoned this project, mainly because of lack of interest from
anyone else and because I'm not working on nanopore data now. I don't know
how much of the code is still relevant!

Regarding the "sim" import, I don't know why it's not there, just delete
the import, the sim module didn't contain anything useful anyway!

**Comment by adelq** [comment]
Alright, thanks.
